apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-aws
  namespace: default
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"  # if we are using the storage class (dynamic pv provision) then we need to use the storage classs name