apiVersion: v1
kind: Service
metadata:
  name: db  #should be db. because the worker pod expected as the same name.
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  selector:
    name: postgres-pod
    app: demo-voting-app
  ports:
    - port: 5432
      targetPort: 5432
