apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /opt/volume/nginx

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
---
apiVersion: v1
kind: Pod
metadata:
  name: logger
  labels:
    run: logger 
spec:
  containers:
    - name: logger
      image: nginx:alpine
      volumeMounts:
        - mountPath: /var/www/nginx
          name: log
  volumes:
    - name: log
      # This AWS EBS volume must already exist.
      persistentVolumeClaim:
        claimName: log-claim