apiVersion: v1
kind: Pod
metadata:
  name: time-check
  labels:
    name: time-check
  namespace: dvl1987
spec:
  containers:
    - name: time-check
      image: busybox
      envFrom:
        - configMapRef:
            name: time-config
      command:
        [
          "/bin/sh",
          "-c",
          "while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log"
        ]
      volumeMounts:
        - mountPath: /opt/time
          name: time-check-voulume
  volumes:
    - name: time-check-voulume
      emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: dvl1987
data:
  TIME_FREQ: "10"
