apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx1401
  labels:
    run: nginx
spec:
  containers:
  - name: kcloud/nginx
    imagePullPolicy: IfNotPresent
    image: nginx
    ports:
      - containerPort: 9080
        protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9080
        scheme: HTTP
      periodSeconds: 10
      initialDelaySeconds: 10
      timeoutSeconds: 60
    livenessProbe:
      exec:
        command:
          - "ls"
          - "/var/www/html/file_check"
      initialDelaySeconds: 10
      periodSeconds: 60
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-glzpb
