apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vh-routing
  namespace: default
  labels:
    name: ingress-vh-routing
spec:
  rules:
    - http:
        paths:
          - path: /wear
            backend:
              service:
                name: wear-service
                port:
                  number: 8080
          - path: /video
            backend:
              service:
                name: apparels-service
                port:
                  number: 8080
